PowerActivityInfo = provider(fields = {
    "vcd": "VCD generated by the activity simulation",
    "window": "JSON file containing start_ps and end_ps",
})

PowerReportInfo = provider(fields = {
    "reports": "Power reports indexed by timing corner",
    "state_out": "LibreLane state containing aggregate power metrics",
})
