filegroup(
    name = "shuttle_sources",
    srcs = [
        "Configs.scala",
        "Generator.scala",
        "ShuttleSystem.scala",
        "ShuttleTop.scala",
    ],
    visibility = ["//visibility:public"],
)
