# FMVPU Python package

load("@rules_python//python:defs.bzl", "py_library")


py_library(
    name = "fmvpu",
    srcs = glob(["*.py"]),
    visibility = ["//visibility:public"],
    imports = [".."],
)