# FMVPU Python package

load("@rules_python//python:defs.bzl", "py_library")


py_library(
    name = "fmvpu",
    srcs = glob(["*.py", "new_lane/*.py"]),
    deps = [],
    visibility = ["//visibility:public"],
    imports = [".."],
)