"""Generate an FFT constants header for a specific size N.

Usage:
    python gen_twiddles.py N [--k K] > twiddles.h

Declares:
    #define TWIDDLE_N     N
    #define TWIDDLE_LOG2N log2(N)
    #define SEED_BLOCK_K  <effective_K>
    static const double omega_re[log2(N)];   // real(ω_N^(2^i)) for i = 0..log2(N)-1
    static const double omega_im[log2(N)];   // imag(ω_N^(2^i))
    static double seed_block_re[log2(N)][SEED_BLOCK_K]
        __attribute__((section(".data.vpu64")));
    static double seed_block_im[log2(N)][SEED_BLOCK_K]
        __attribute__((section(".data.vpu64")));
    static double expected_re[N] __attribute__((section(".data.vpu64")));
    static double expected_im[N] __attribute__((section(".data.vpu64")));

omega[i] = ω_N^(2^i), i.e. successive squarings of ω_N = exp(-2πi/N). A few dozen
doubles regardless of N. Seed blocks are `seed_block[j][k] = omega[j]^k`, used by
the kernel's `build_seed` primitive to load twiddle seeds via unit-stride vle64.

expected_{re,im} are the DFT of the test input {0, 1, ..., N-1} + 0j, placed in
VPU memory so on-device correctness checks can run via vector ops.
"""
import argparse
import cmath
import math
import sys

parser = argparse.ArgumentParser()
parser.add_argument("N", type=int, help="FFT size (power of 2)")
parser.add_argument("--k", type=int, default=128,
                    help="Seed block column count (capped to min(K, N))")
parser.add_argument("--corrupt-expected", action="store_true",
                    help="Emit a deliberately wrong `expected` array so a "
                    "passing FFT is reported as FAIL. Used by the sanity "
                    "negative test that guards against vacuous passes.")
args = parser.parse_args()

N = args.N
assert N > 0 and (N & (N - 1)) == 0, "N must be a power of 2"

log2_n = N.bit_length() - 1
seed_block_k = min(args.k, N)
out = sys.stdout


def emit_array(decl, values):
    out.write(decl + " = {\n")
    for v in values:
        out.write(f"    {v:.17e},\n")
    out.write("};\n\n")


def emit_2d_array(decl, rows):
    out.write(decl + " = {\n")
    for row in rows:
        out.write("    {\n")
        for v in row:
            out.write(f"        {v:.17e},\n")
        out.write("    },\n")
    out.write("};\n\n")


out.write("/* Auto-generated by gen_twiddles.py. Do not edit. */\n")
out.write("#ifndef TWIDDLES_H\n#define TWIDDLES_H\n\n")
out.write(f"#define TWIDDLE_N {N}\n")
out.write(f"#define TWIDDLE_LOG2N {log2_n}\n")
out.write(f"#define SEED_BLOCK_K {seed_block_k}\n\n")

# omega[i] = ω_N^(2^i) = exp(-2πi · 2^i / N) for i = 0..log2(N)-1.
# Successive squarings of ω_N; a few dozen doubles regardless of N. The FFT
# init code builds per-stage seed vectors from these by iterative
# multiplication.
omegas = [cmath.exp(-2j * math.pi * (1 << i) / N) for i in range(log2_n)]
emit_array(f"static const double omega_re[{log2_n}]", [w.real for w in omegas])
emit_array(f"static const double omega_im[{log2_n}]", [w.imag for w in omegas])

# seed_block[j][k] = omega[j]^k for j in [0, log2N), k in [0, SEED_BLOCK_K).
# Used by build_seed(): unit-stride vle64 of one row fills a length-SEED_BLOCK_K
# vector register; longer seeds extend by doubling with a scalar multiply.
seed_rows_re = []
seed_rows_im = []
for j in range(log2_n):
    w = omegas[j]
    row = [w ** k for k in range(seed_block_k)]
    seed_rows_re.append([v.real for v in row])
    seed_rows_im.append([v.imag for v in row])

emit_2d_array(
    f'static double seed_block_re[{log2_n}][{seed_block_k}]'
    ' __attribute__((section(".data.vpu64")))',
    seed_rows_re)
emit_2d_array(
    f'static double seed_block_im[{log2_n}][{seed_block_k}]'
    ' __attribute__((section(".data.vpu64")))',
    seed_rows_im)

# Expected DFT output for input {0, 1, ..., N-1} + 0j. Direct O(N²) — fine for
# N up to a few thousand; for larger N replace with a numpy.fft.fft call.
input_vals = [complex(float(i), 0.0) for i in range(N)]
expected = [sum(input_vals[j] * cmath.exp(-2j * math.pi * k * j / N)
                for j in range(N))
            for k in range(N)]

if args.corrupt_expected:
    # Flip element 0's real part so the on-device check must report FAIL.
    # Scale is well above the kernel's TOL (1e-3 today).
    expected[0] = expected[0] + complex(1.0, 0.0)

emit_array(f'static double expected_re[{N}] __attribute__((section(".data.vpu64")))',
           [v.real for v in expected])
emit_array(f'static double expected_im[{N}] __attribute__((section(".data.vpu64")))',
           [v.imag for v in expected])

out.write("#endif\n")
