import logging
from typing import List, Tuple

from zamlet import addresses
from zamlet.addresses import KMAddr
from zamlet.params import ZamletParams
from zamlet.jamlet.jamlet import Jamlet
from zamlet.message import Header, MessageType, SendType, AddressHeader, WriteMemWordHeader
from zamlet.utils import Queue
from zamlet.kamlet import kinstructions
from zamlet.kamlet.kinstructions import has_reg_ordering_conflict
from zamlet.kamlet.rename_table import RegisterRenameTable
from zamlet.synchronization import Synchronizer
from zamlet import register_file_slot
from zamlet.kamlet.cache_table import (
    CacheRequestType, CacheTable, WaitingItem, SendState, ReceiveState,
    has_memory_ordering_conflict, has_cache_line_conflict,
)
from zamlet.transactions.write_imm_bytes import WaitingWriteImmBytes
from zamlet.transactions.read_byte import WaitingReadByte
from zamlet.monitor import Monitor, WitemSnapshot, KamletSnapshot


logger = logging.getLogger(__name__)





class Kamlet:
    """
    A collection of lanes.
    They share an instruction buffer, and cache tracking logic.
    """

    def __init__(self, clock, params: ZamletParams, min_x: int, min_y: int, tlb: addresses.TLB,
                 monitor: Monitor, lamlet_x: int, lamlet_y: int,
                 mem_coords: List[Tuple[int, int]]):
        self.clock = clock
        self.params = params
        self.monitor = monitor
        self.lamlet_x = lamlet_x
        self.lamlet_y = lamlet_y

        # A kamlet covers several (x,y) coordinate positions (one for each lane (jamlet))
        self.min_x = min_x
        self.min_y = min_y
        self.n_columns = params.j_cols
        self.n_rows = params.j_rows
        self.n_jamlets = self.n_columns * self.n_rows

        self.mem_coords = mem_coords
        self.mem_x = mem_coords[0][0]
        self.mem_y = mem_coords[0][1]

        # We pass methods to the cache table to flush and read lines.
        name = f'CacheTable ({self.min_x}, {self.min_y})'
        self.cache_table = CacheTable(clock, params, name, monitor,
                                      kamlet_x=self.min_x, kamlet_y=self.min_y)
        rf_name = f'kamlet({self.min_x},{self.min_y})'
        self.rf_info = register_file_slot.KamletRegisterFile(self.params.n_vregs, name=rf_name)
        # Per-kamlet rename table. Arch indices in kinstructions are translated
        # to phys indices at dispatch; the scoreboard operates on phys.
        self.rename_table = RegisterRenameTable(params)
        self.tlb = tlb

        # One synchronizer per kamlet for tracking when operations complete across kamlets
        kx = (self.min_x - params.west_offset) // params.j_cols
        ky = (self.min_y - params.north_offset) // params.j_rows
        self.synchronizer = Synchronizer(clock, params, kx, ky, self.cache_table, monitor)

        n_mem_routers = len(mem_coords)
        jamlets_per_router = self.n_jamlets // n_mem_routers
        self.jamlets = []
        for index in range(self.n_jamlets):
            x = min_x+index % self.n_columns
            y = min_y+index//self.n_columns
            j_mem_coords = mem_coords[index // jamlets_per_router]
            self.jamlets.append(Jamlet(clock, params, x, y, self.cache_table, self.rf_info,
                                       self.tlb, monitor, lamlet_x, lamlet_y,
                                       mem_xy=j_mem_coords))

        # Local State
        # 0 = no bound (full 64-bit indices), N = mask indices to lower N bits
        self.index_bound_bits: int = 0

        self._instruction_queue = Queue(self.params.instruction_queue_length)

        # Reservation station: fixed-depth array of slots. A slot holds an
        # admitted station-path instruction or None if free. Scanned
        # oldest-first (by renamed.order) at dispatch.
        self._reservation_station: list = [None] * self.params.reservation_station_depth
        self._next_order: int = 0

        # We place packets here that are generated by instructions.
        self._instr_send_queue = Queue(2)


    def r(self, arch: int) -> int:
        """Look up the phys currently mapped to arch. Used for pure source regs
        (add result to scoreboard read_regs)."""
        return self.rename_table.lookup_read(arch)

    async def w(self, arch: int, exclude_reuse: set[int] | None = None) -> int:
        """Allocate a fresh phys for arch and return it. Used for pure dest regs
        (add result to scoreboard write_regs).

        If arch is already mapped and its current phys is idle (no RF
        locks, no station references), reuse that phys instead of
        rotating. Nothing depends on the prior value, so overwriting
        in place preserves correctness and avoids draining free_queue
        on every write.

        Otherwise awaits next_cycle while the real free_queue is empty
        so drain_pending (invoked from kamlet.update() each cycle) has
        a chance to release pregs from pending_free. This provides
        backpressure on register-renaming bursts without hard-failing
        on transient exhaustion.

        exclude_reuse: pregs the current kinstr already uses as sources.
        Reusing one of them as dst would alias a read and write within
        the same kinstr, which the rename/scoreboard design forbids.
        Pass `set(source_pregs)` from the caller (e.g. indexed gather
        when dst arch == index arch after register coalescing).
        """
        exclude = exclude_reuse or set()
        if self.rename_table.is_mapped(arch):
            current = self.rename_table.arch[arch]
            if current not in exclude and self._is_preg_idle(current):
                return current
        waited = 0
        while not self.rename_table.free_queue:
            # Re-check the reuse path: the preg currently mapped to arch
            # may have become idle while we were waiting (witems finalized,
            # station references released). Reusing it lets us make
            # forward progress when free_queue is empty and won't refill
            # because no FreeRegister can be admitted behind us.
            if self.rename_table.is_mapped(arch):
                current = self.rename_table.arch[arch]
                if current not in exclude and self._is_preg_idle(current):
                    return current
            if waited == 0:
                logger.debug(
                    f'{self.clock.cycle}: kamlet ({self.min_x},{self.min_y}) '
                    f'w(arch={arch}) waiting — pending_free='
                    f'{sorted(self.rename_table.pending_free)} '
                    f'station_idents='
                    f'{[(getattr(i, "instr_ident", "?") if i else None) for i in self._reservation_station]}')
            waited += 1
            if waited % 500 == 0:
                logger.warning(
                    f'{self.clock.cycle}: kamlet ({self.min_x},{self.min_y}) '
                    f'w(arch={arch}) stuck {waited} cycles. '
                    f'pending_free={sorted(self.rename_table.pending_free)} '
                    f'station_idents='
                    f'{[(getattr(i, "instr_ident", "?") if i else None) for i in self._reservation_station]}')
                for p in sorted(self.rename_table.pending_free):
                    refs = []
                    if self.rf_info.write[p] is not None:
                        refs.append(f'rf_write={self.rf_info.write[p]}')
                    if self.rf_info.reads[p]:
                        refs.append(f'rf_reads={self.rf_info.reads[p]}')
                    for idx, instr in enumerate(self._reservation_station):
                        if instr is None: continue
                        r = instr.renamed
                        if p in r.read_pregs:
                            refs.append(f'station[{idx}].read ident={instr.instr_ident}')
                        if p in r.write_pregs:
                            refs.append(f'station[{idx}].write ident={instr.instr_ident}')
                    logger.warning(f'  pending preg {p}: {refs}')
            await self.clock.next_cycle
        return self.rename_table.allocate_write(arch)

    def rw(self, arch: int) -> int:
        """Return the existing phys for arch without rotating the rename table.

        Used for read-modify-write operations (e.g. vmacc accumulator) where
        rename rotation would drain the free queue without enabling cross-
        iteration pipelining (the RAW dep across iterations is inherent).
        Caller should put the returned phys in scoreboard write_regs only;
        the write lock covers both the accumulator read and write.
        """
        return self.rename_table.lookup_read(arch)

    async def alloc_dst_pregs(self, base_arch: int, start_vline: int, end_vline: int,
                              start_index: int, n_elements: int, elements_in_vline: int,
                              mask_present: bool,
                              exclude_reuse: set[int] | None = None) -> List[int]:
        """Allocate dst phys regs for a multi-vline op under the current
        fully-undisturbed policy (vta=vma=False).

        Per-vline rule:
          - Arch is unmapped (first write to a freshly allocated scratch
            arch): w() unconditionally — there is no prior value to
            preserve, so prestart/tail/inactive positions hold garbage but
            that is the caller's expectation when they allocated a fresh
            scratch reg.
          - First vline with prestart (start_index unaligned): rw() — prestart
            is always undisturbed per RVV spec.
          - Mask present: rw() for every vline — masked-off elements are
            undisturbed (vma=False).
          - Last vline with tail (n_elements unaligned): rw() — tail is
            undisturbed (vta=False).
          - Otherwise: w() — fully written, safe to rotate.

        Returns a list of phys regs in vline order (one per vline in
        [start_vline, end_vline]).

        Tracked: vta/vma support is planned in `docs/PLAN_vta_vma.md`. Once
        agnostic policies are honored, fully-rotated allocation will be
        possible for partial vlines under vta=True / vma=True.
        """
        n_vlines = end_vline - start_vline + 1
        head_unaligned = (start_index % elements_in_vline) != 0
        tail_unaligned = ((start_index + n_elements) % elements_in_vline) != 0
        pregs: List[int] = []
        for i in range(n_vlines):
            vline_idx = start_vline + i
            arch = base_arch + vline_idx
            # First write to a freshly allocated scratch arch: nothing to
            # preserve, w() unconditionally (also: rw() would assert).
            if not self.rename_table.is_mapped(arch):
                pregs.append(await self.w(arch, exclude_reuse=exclude_reuse))
                continue
            # Under fully-undisturbed (vma=False), masked op needs rw() on
            # every vline because mask-off positions could fall anywhere.
            if mask_present:
                pregs.append(self.rw(arch))
                continue
            is_first = (vline_idx == start_vline)
            is_last = (vline_idx == end_vline)
            partial = (is_first and head_unaligned) or (is_last and tail_unaligned)
            if partial:
                pregs.append(self.rw(arch))
            else:
                pregs.append(await self.w(arch, exclude_reuse=exclude_reuse))
        return pregs

    def rf_available(self, read_regs=None, write_regs=None):
        if read_regs is None:
            read_regs = []
        if write_regs is None:
            write_regs = []
        avail = (all(self.rf_info.can_read(r) for r in read_regs) and
                 all(self.rf_info.can_write(r) for r in write_regs))
        #for reg in read_regs:
        #    if not self.rf_info.can_read(reg):
        #        logger.debug(f'kamlet {(self.min_x, self.min_y)}: Cannot read {reg}')
        #for reg in write_regs:
        #    if not self.rf_info.can_write(reg):
        #        logger.debug(f'kamlet {(self.min_x, self.min_y)}: Cannot write {reg}')
        return avail

    def is_ready(self, instr, station) -> bool:
        """Check if a reservation station entry is ready to dispatch.

        station is the list of KInstrs currently in the reservation station
        (each with a .renamed set). Memory-ordering checks scan both the
        station (for entries with a lower `order`) and the cache_table's
        waiting_items (already-dispatched witems, older by construction).
        """
        renamed = instr.renamed
        if not self.rf_available(read_regs=renamed.read_pregs,
                                 write_regs=renamed.write_pregs):
            return False
        for other_instr in station:
            if other_instr is None or other_instr is instr:
                continue
            other = other_instr.renamed
            if other.order >= renamed.order:
                continue
            if has_memory_ordering_conflict(renamed, other):
                return False
            if has_reg_ordering_conflict(renamed, other):
                return False
            if has_cache_line_conflict(
                    instr, other_instr, self.params.cache_line_bytes):
                return False
        for other in self.cache_table.waiting_items:
            if has_memory_ordering_conflict(renamed, other):
                return False
        if renamed.needs_witem and not self.cache_table.has_free_witem_slot(
                n=renamed.needs_witem):
            return False
        if renamed.cache_is_read or renamed.cache_is_write:
            if not self.cache_table.can_get_slot(instr.k_maddr):
                return False
            slot = self.cache_table.addr_to_slot(instr.k_maddr)
            if slot is not None:
                ws = renamed.writeset_ident
                if renamed.cache_is_write:
                    if self.cache_table.slot_in_use(slot, writeset_ident=ws):
                        return False
                if renamed.cache_is_read:
                    if self.cache_table.slot_has_write(slot, writeset_ident=ws):
                        return False
        return True

    async def wait_for_rf_available(self, read_regs=None, write_regs=None, instr_ident: int | None = None):
        if self.rf_available(read_regs, write_regs):
            return
        if instr_ident is not None:
            self.monitor.record_rf_blocking(
                instr_ident, self.min_x, self.min_y,
                read_regs, write_regs, self.rf_info, self.cache_table.waiting_items)
        while not self.rf_available(read_regs, write_regs):
            await self.clock.next_cycle

    def update(self):
        self._instruction_queue.update()
        self._instr_send_queue.update()
        self.cache_table.update()
        self.synchronizer.update()
        for jamlet in self.jamlets:
            jamlet.update()

    async def _drain_pending_pregs(self):
        """Release pregs from rename_table.pending_free to free_queue when
        they are no longer referenced. Runs once per cycle independent of
        the admit/dispatch coroutines so free_queue refills even when those
        are blocked."""
        while True:
            await self.clock.next_cycle
            for preg in list(self.rename_table.pending_free):
                if self._is_preg_idle(preg):
                    self.rename_table.release_pending(preg)

    def _is_preg_idle(self, preg: int) -> bool:
        """Callback for rename_table.drain_pending. A pending preg is
        safe to return to free_queue only when nothing currently holds
        it: no RF lock (write or read), no reservation station entry
        references it in its renamed preg lists.
        """
        if self.rf_info.write[preg] is not None:
            return False
        if self.rf_info.reads[preg]:
            return False
        for instr in self._reservation_station:
            if instr is None:
                continue
            r = instr.renamed
            if preg in r.read_pregs or preg in r.write_pregs:
                return False
        return True

    @property
    def k_index(self):
        kx = (self.min_x - self.params.west_offset) // self.params.j_cols
        ky = (self.min_y - self.params.north_offset) // self.params.j_rows
        return ky * self.params.k_cols + kx

    def get_regs(self, start_index: int, n_elements: int, base_reg: int, ew: int):
        '''
        Given a start_index and n_elements and a base register work out which vector registers
        get touched (in any kamlet, but that's good enough)
        '''
        elements_in_vline = self.params.vline_bytes * 8 // ew
        start_vline = start_index // elements_in_vline
        end_vline = (start_index + n_elements - 1) // elements_in_vline
        regs = [base_reg + vline_offset for vline_offset in range(start_vline, end_vline + 1)]
        return regs

    def get_jamlet(self, x, y):
        assert self.min_x <= x < self.min_x + self.n_columns
        assert self.min_y <= y < self.min_y + self.n_rows
        jamlet = self.jamlets[(y - self.min_y) * self.n_columns + (x - self.min_x)]
        assert jamlet.x == x
        assert jamlet.y == y
        return jamlet

    def get_oldest_active_instr_ident_distance(self, baseline: int) -> int | None:
        """Distance to the oldest active instr_ident from baseline across the
        kamlet's live state — reservation-station entries (admitted but not yet
        dispatched to a witem) and cache_table waiting_items.

        Distance is (ident - baseline) % max_response_tags, so older idents have
        smaller distances. Returns None when no live ident exists (all free).
        """
        max_tags = self.params.max_response_tags
        idents: list[int] = []
        for instr in self._reservation_station:
            if instr is None:
                continue
            ident = getattr(instr, 'instr_ident', None)
            if ident is not None and ident < max_tags:
                idents.append(ident)
        for item in self.cache_table.waiting_items:
            if item.instr_ident is not None and item.instr_ident < max_tags:
                idents.append(item.instr_ident)
        if not idents:
            logger.debug(
                f'{self.clock.cycle}: kamlet ({self.min_x},{self.min_y}) '
                f'get_oldest_active_instr_ident_distance: '
                f'baseline={baseline} idents=[] -> None')
            return None
        distances = []
        for ident in idents:
            d = (ident - baseline) % max_tags
            if d == 0:
                d = max_tags  # at baseline is newest, not oldest
            distances.append(d)
        result = min(distances)
        logger.debug(
            f'{self.clock.cycle}: kamlet ({self.min_x},{self.min_y}) '
            f'get_oldest_active_instr_ident_distance: '
            f'baseline={baseline} idents={idents} distances={distances} min={result}')
        if result == max_tags:
            return None
        return result

    def add_to_instruction_queue(self, instr: kinstructions.KInstr):
        assert isinstance(instr, kinstructions.KInstr)
        instr_name = type(instr).__name__
        instr_ident = getattr(instr, 'instr_ident', '?')
        logger.debug(f'{self.clock.cycle}: kamlet ({self.min_x},{self.min_y}) RECEIVE INSTRUCTION {instr_name} ident={instr_ident}')
        self._instruction_queue.append(instr)
        self.monitor.record_kamlet_instr_added(self.min_x, self.min_y)

    def _snapshot_witems(self) -> list[WitemSnapshot]:
        """Snapshot current WITEM state for visualization."""
        snapshots = []
        for witem in self.cache_table.waiting_items:
            name = type(witem).__name__
            ident = witem.instr_ident
            states = getattr(witem, 'transaction_states', None)
            if states is not None:
                tag_states = []
                for s in states:
                    if s in (SendState.INITIAL, SendState.NEED_TO_SEND,
                             SendState.WAITING_IN_CASE_FAULT):
                        tag_states.append(1)  # unsent (red)
                    elif s == SendState.WAITING_FOR_RESPONSE:
                        tag_states.append(2)  # pending (blue)
                    elif s == SendState.COMPLETE:
                        tag_states.append(3)  # complete (green)
                    else:
                        tag_states.append(0)
            else:
                tag_states = [3 if witem.ready() else 1]
            snapshots.append(WitemSnapshot(
                name=name, instr_ident=ident, tag_states=tag_states))
        return snapshots

    async def _monitor_instruction_queue(self):
        while True:
            await self.clock.next_cycle
            self.monitor.record_kamlet_cycle_state(
                self.min_x, self.min_y, len(self._instruction_queue),
            )
            # Snapshot instruction queue + WITEM state
            next_instrs = []
            for instr in list(self._instruction_queue.queue)[:2]:
                iname = type(instr).__name__
                iident = getattr(instr, 'instr_ident', -1)
                next_instrs.append((iname, iident))
            snapshot = KamletSnapshot(
                next_instructions=next_instrs,
                witems=self._snapshot_witems(),
            )
            self.monitor.record_kamlet_snapshot(
                self.min_x, self.min_y, snapshot)

    async def _admit_instructions(self):
        while True:
            await self.clock.next_cycle
            if not self._instruction_queue:
                continue
            free_slot = None
            for i, slot in enumerate(self._reservation_station):
                if slot is None:
                    free_slot = i
                    break
            if free_slot is None:
                continue
            instruction = self._instruction_queue.popleft()
            self.monitor.record_kamlet_instr_removed(self.min_x, self.min_y)
            instr_name = type(instruction).__name__
            instr_ident = getattr(instruction, 'instr_ident', '?')
            span_id = self.monitor.get_kinstr_exec_span_id(
                instr_ident, self.min_x, self.min_y)
            self.monitor.add_event(span_id, "admitted")
            logger.info(
                f'{self.clock.cycle}: kamlet ({self.min_x},{self.min_y})'
                f' instr_queue: {len(self._instruction_queue)}'
                f' ADMIT {instr_name} ident={instr_ident}')
            admitted = await instruction.admit(self)
            if admitted is not None:
                assert admitted.renamed is not None
                admitted.renamed.order = self._next_order
                self._next_order += 1
                self._reservation_station[free_slot] = admitted

    async def _dispatch_from_reservation_station(self):
        while True:
            await self.clock.next_cycle
            chosen_index = None
            chosen_order = None
            for i, instr in enumerate(self._reservation_station):
                if instr is None:
                    continue
                if not self.is_ready(instr, self._reservation_station):
                    continue
                if chosen_order is None or instr.renamed.order < chosen_order:
                    chosen_order = instr.renamed.order
                    chosen_index = i
            if chosen_index is None:
                continue
            instruction = self._reservation_station[chosen_index]
            instr_name = type(instruction).__name__
            instr_ident = getattr(instruction, 'instr_ident', '?')
            logger.info(
                f'{self.clock.cycle}: kamlet ({self.min_x},{self.min_y})'
                f' DISPATCH {instr_name} ident={instr_ident}'
                f' order={instruction.renamed.order}')
            await instruction.execute(self)
            self._reservation_station[chosen_index] = None

    async def _monitor_cache_requests(self):
        while True:
            await self.clock.next_cycle
            for request in self.cache_table.cache_requests:
                if request is None:
                    continue
                if request.is_fully_sent():
                    continue
                if request.request_type == CacheRequestType.READ_LINE:
                    if not request.addr_sent:
                        await self.read_cache_line(
                            cache_slot=request.slot,
                            address_in_memory=request.addr,
                            ident=request.ident)
                        self.cache_table.report_addr_sent(request)
                elif request.request_type in (
                    CacheRequestType.WRITE_LINE,
                    CacheRequestType.WRITE_LINE_READ_LINE,
                ):
                    slot_state = self.cache_table.slot_states[request.slot]
                    write_address = request.addr
                    if not request.addr_sent:
                        if request.request_type == CacheRequestType.WRITE_LINE:
                            await self.jamlets[0].send_write_line_addr(
                                cache_slot=request.slot,
                                write_address=write_address,
                                ident=request.ident)
                        else:
                            read_address = (
                                slot_state.memory_loc * self.params.cache_line_bytes)
                            await self.jamlets[0].send_write_line_read_line_addr(
                                cache_slot=request.slot,
                                write_address=write_address,
                                read_address=read_address,
                                ident=request.ident)
                        self.cache_table.report_addr_sent(request)
                    else:
                        for j_in_k_index, jamlet in enumerate(self.jamlets):
                            if not request.data_sent[j_in_k_index]:
                                await jamlet.send_write_line_data(
                                    cache_slot=request.slot,
                                    ident=request.ident)
                                self.cache_table.report_data_sent(
                                    request, j_in_k_index)

    async def _get_instructions_from_jamlets(self):
        while True:
            await self.clock.next_cycle
            # Get received instructions from jamlets
            for index, jamlet in enumerate(self.jamlets):
                if jamlet._instruction_buffer:
                    if index == 0:
                        if self._instruction_queue.can_append():
                            instr = jamlet._instruction_buffer.popleft()
                            self.add_to_instruction_queue(instr)
                    else:
                        instr = jamlet._instruction_buffer.popleft()

    async def run(self):
        for jamlet in self.jamlets:
            self.clock.create_task(jamlet.run())
        self.clock.create_task(self._admit_instructions())
        self.clock.create_task(self._dispatch_from_reservation_station())
        self.clock.create_task(self._drain_pending_pregs())
        self.clock.create_task(self._monitor_instruction_queue())
        self.clock.create_task(self._send_packets())
        self.clock.create_task(self._get_instructions_from_jamlets())
        self.clock.create_task(self._monitor_cache_requests())
        self.clock.create_task(self._monitor_witems())
        self.clock.create_task(self.cache_table.run())
        self.clock.create_task(self.synchronizer.run())

    async def _queue_cache_request(self, packet, slot: int):
        """Queue a cache request packet and record the message sent."""
        header = packet[0]
        while not self._instr_send_queue.can_append():
            await self.clock.next_cycle
        self._instr_send_queue.append(packet)

        cache_request_span_id = self.monitor.get_cache_request_span_id(
            self.min_x, self.min_y, slot)
        self.monitor.record_message_sent(
            cache_request_span_id, header.message_type.name,
            ident=header.ident, tag=slot,
            src_x=header.source_x, src_y=header.source_y,
            dst_x=header.target_x, dst_y=header.target_y)

    async def read_cache_line(self, cache_slot: int, address_in_memory: int, ident: int):
        """
        Reads from memory into the cache line.
        This function should only be called by our CacheTable.
        We pass it to the cache table's constructor.
        """
        logger.debug('{self.clock.cycle}: kamlet {(self.min_x, self.min_y)}: read_cache_line')
        address_in_sram = cache_slot * self.params.cache_line_bytes // self.params.j_in_k
        send_jamlet = self.jamlets[self.params.send_read_line_j_index]

        header = AddressHeader(
            message_type=MessageType.READ_LINE_ADDR, #4
            send_type=SendType.SINGLE,          #1
            target_x=self.mem_x,                #8
            target_y=self.mem_y,                #8
            source_x=send_jamlet.x,             #8
            source_y=send_jamlet.y,             #8
            address=address_in_sram,            #12
            length=1,                           #5
            ident=ident,               #5 bits
            )
        assert address_in_memory % self.params.cache_line_bytes == 0
        packet = [header, address_in_memory]

        await self._queue_cache_request(packet, cache_slot)

    def get_is_active(self, start_index, n_elements, element_width, word_order, mask_reg, vline_index, j_in_k_index, index_in_j):
        '''
        Consider an element specified by:
          what vline_index in the vector it is
          what j_in_k_index it is in (what jamlet in the kamlet)
          what element it is in that work (index_in_j)
          what reg we're using for the masks
          we know what k_index is because we know what kamlet we are
        '''
        ww = self.params.word_bytes * 8
        ew = element_width
        elements_in_vline = self.params.vline_bytes*8//ew
        jamlet = self.jamlets[j_in_k_index]
        vw_index = addresses.k_indices_to_vw_index(
                self.params, word_order, self.k_index, j_in_k_index)
        element_index = vline_index*elements_in_vline + index_in_j * self.params.j_in_l + vw_index
        valid_element = start_index <= element_index < n_elements
        if mask_reg is not None:
            mask_bit_addr = mask_reg * ww + element_index//self.params.j_in_l
            mask_byte = jamlet.rf_slice[mask_bit_addr//8]
            mask_bit = (mask_byte >> (mask_bit_addr % 8)) & 1
        else:
            mask_bit = 1
        return valid_element, mask_bit

    async def handle_item(self, witem: WaitingItem) -> None:
        await witem.finalize(self)
        source_x, source_y = None, None
        if witem.source is not None:
            source_x, source_y = witem.source
        self.monitor.complete_witem(witem.instr_ident, self.min_x, self.min_y,
                                    source_x=source_x, source_y=source_y)

    async def _monitor_witems(self) -> None:
        while True:
            await self.clock.next_cycle
            witems = list(self.cache_table.waiting_items)
            #if witems:
            #    summaries = []
            #    for item in witems:
            #        name = type(item).__name__
            #        ident = item.instr_ident
            #        states = getattr(item, 'transaction_states', None)
            #        if states is not None:
            #            from zamlet.kamlet.cache_table import SendState
            #            counts = {}
            #            for s in states:
            #                counts[s.name[0]] = counts.get(s.name[0], 0) + 1
            #            state_str = '/'.join(f'{v}{k}' for k, v in counts.items())
            #        else:
            #            state_str = 'ready' if item.ready() else 'pending'
            #        summaries.append(f'{name}[{ident}]:{state_str}')
            #    logger.info(
            #        f'{self.clock.cycle}: kamlet ({self.min_x},{self.min_y}) '
            #        f'monitor_witems: {len(witems)} items: '
            #        + ', '.join(summaries))
            for item in witems:
                if item not in self.cache_table.waiting_items:
                    continue
                await item.monitor_kamlet(self)
                if item.ready():
                    self.cache_table.waiting_items.remove(item)
                    await self.handle_item(item)
                    break

    async def _send_packets(self) -> None:
        while True:
            await self.clock.next_cycle
            if self._instr_send_queue:
                packet = self._instr_send_queue.popleft()
                send_index = self.params.send_read_line_j_index
                buffer = self.jamlets[send_index].send_queues[packet[0].message_type]
                while not buffer.can_append():
                    await self.clock.next_cycle
                buffer.append(packet)
