# Config files for FMVPU

# List of FMVPU config JSON files
LANE_ARRAY_CONFIG_FILES = [
    "lane_array_default.json",
]

# List of Lane config JSON files
LANE_CONFIG_FILES = [
    "lane_default.json",
]

exports_files(LANE_ARRAY_CONFIG_FILES + LANE_CONFIG_FILES, visibility = ["//visibility:public"])
