# Config files for FMVPU

# List of FMVPU config JSON files
LANE_ARRAY_CONFIG_FILES = [
    "lane_array_default.json",
]

# List of Lane config JSON files
LANE_CONFIG_FILES = [
    "lane_default.json",
]

# List of Amlet config JSON files
AMLET_CONFIG_FILES = [
    "amlet_default.json",
]

# List of Bamlet config JSON files
BAMLET_CONFIG_FILES = [
    "bamlet_default.json",
]

# List of Gamlet config JSON files
GAMLET_CONFIG_FILES = [
    "gamlet_default.json",
]

exports_files(LANE_ARRAY_CONFIG_FILES + LANE_CONFIG_FILES + AMLET_CONFIG_FILES + BAMLET_CONFIG_FILES + GAMLET_CONFIG_FILES, visibility = ["//visibility:public"])
