# Config files for FMVPU

# List of Jamlet config JSON files
JAMLET_CONFIG_FILES = [
    "jamlet_default.json",
]

# List of Kamlet config JSON files
KAMLET_CONFIG_FILES = [
    "synchronizer_default.json",
]

# List of Lamlet config JSON files
LAMLET_CONFIG_FILES = [
    "lamlet_default.json",
]

# List of Maths config JSON files
MATHS_CONFIG_FILES = [
    "WallaceMult8x8.json",
    "WallaceMult16x16.json",
    "WallaceMult32x32.json",
    "WallaceMult64x64.json",
]

# List of Utils config JSON files
UTILS_CONFIG_FILES = [
    "dropping_fifo_default.json",
]

exports_files(
    JAMLET_CONFIG_FILES + KAMLET_CONFIG_FILES + LAMLET_CONFIG_FILES + MATHS_CONFIG_FILES +
    UTILS_CONFIG_FILES,
    visibility = ["//visibility:public"]
)
