# BUILD file for flow directory

exports_files([
    "dump_pdk_config.py",
    "librelane_plugin_zamlet/__init__.py",
    "librelane_plugin_zamlet/sta_mid_pnr.py",
])

py_binary(
    name = "summarize_macro",
    srcs = ["summarize_macro.py"],
    main = "summarize_macro.py",
    visibility = ["//visibility:public"],
)
