site_name: Zamlet
nav:
  - Home: index.md
  - Overview and Concepts:
    - Hierarchy: hierarchy.md
    - Instruction Flow: instruction_flow.md
    - Stripes, Lane Order and Element Width: stripe.md
    - Memory Model: memory_model.md
  - Architecture:
    - Lamlet: lamlet.md
    - Kamlet: kamlet.md
    - Jamlet: kamlet.md
    - Network: network.md
    - Synchronization: synchronization.md
    - IdentQuery: ident_query.md
  - Examples:
    - Gather Example: gather_example.md
  - Use:
    - Setup: setup.md
    - Python Model: python.md
  - Misc:
    - LLM Usage: llm.md
    - Current State: scope.md
theme:
  name: readthedocs
  highlightjs: false
